#services:
  #mock-lead-gen-backend:
    #build: 
      #context: ./
      #dockerfile: dockerfile
    #container_name: mock-lead-gen-backend
    #ports: 
      #- "5050:5050"
    #environment:
      #FLASK_APP: main.py
      #FLASK_RUN_HOST: 0.0.0.0
      #POSTGRES_DB: mock_lead_gen_db
      #POSTGRES_USER: mock_lead_gen_user
      #POSTGRES_PASSWORD: mock_lead_gen_password
      #POSTGRES_HOST: mock-lead-gen-db
      #POSTGRES_PORT: 5432
    #networks:
      #- mock-lead-gen-network
    #restart: always

#networks:
  #mock-lead-gen-network:
    #external: true

services:
  mock-lead-gen-db:
    image: postgres:17
    container_name: mock-lead-gen-db
    restart: always
    environment:
      POSTGRES_DB: mock_lead_gen_db
      POSTGRES_USER: mock_lead_gen_user
      POSTGRES_PASSWORD: mock_lead_gen_password
    volumes:
      - mock_lead_gen_pgdata:/var/lib/postgresql/data
    networks:
      - mock-lead-gen-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mock_lead_gen_user -d mock_lead_gen_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  mock-lead-gen-backend:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: mock-lead-gen-backend
    ports:
      - "5050:5050"
    environment:
      FLASK_APP: main.py
      FLASK_RUN_HOST: 0.0.0.0
      POSTGRES_DB: mock_lead_gen_db
      POSTGRES_USER: mock_lead_gen_user
      POSTGRES_PASSWORD: mock_lead_gen_password
      POSTGRES_HOST: mock-lead-gen-db
      POSTGRES_PORT: 5432
    depends_on:
      mock-lead-gen-db:
        condition: service_healthy
    networks:
      - mock-lead-gen-network
    restart: always

volumes:
  mock_lead_gen_pgdata:
