null = ""
false = False
true = True
enriched =[{
  "status": "success",
  "error_code": null,
  "error_message": null,
  "total_requested_domains": 6,
  "unique_domains": 6,
  "unique_enriched_records": 6,
  "missing_records": 0,
  "organizations": [
    {
      "id": "60f3c5498dbf150001e70682",
      "name": "Weave",
      "website_url": "http://www.getweave.com",
      "blog_url": null,
      "angellist_url": null,
      "linkedin_url": "http://www.linkedin.com/company/getweave",
      "twitter_url": "https://twitter.com/getweave",
      "facebook_url": "https://facebook.com/weavecomm/",
      "primary_phone": {
        "number": "+1 888-579-5668",
        "source": "Owler",
        "sanitized_number": "+18885795668"
      },
      "languages": [],
      "alexa_ranking": 158005,
      "phone": "+1 888-579-5668",
      "linkedin_uid": "1271877",
      "founded_year": 2008,
      "publicly_traded_symbol": "WEAV",
      "publicly_traded_exchange": "nasdaq",
      "logo_url": "https://zenprospect-production.s3.amazonaws.com/uploads/pictures/68ae122440c2c6000190c421/picture",
      "crunchbase_url": null,
      "primary_domain": "getweave.com",
      "sanitized_phone": "+18885795668",
      "market_cap": "597.8M",
      "industry": "information technology & services",
      "estimated_num_employees": 860,
      "keywords": [
        "dental",
        "optometry",
        "salon",
        "veterinary",
        "small business",
        "small business owners",
        "health care",
        "dental specialties",
        "medical",
        "medical spas",
        "physical therapy",
        "podiatry",
        "communication software",
        "digital forms",
        "web assistant",
        "phones",
        "messages",
        "sms messaging",
        "customer insights",
        "customer reviews",
        "scheduling",
        "payments",
        "team chat",
        "analytics",
        "desktop software",
        "mobile app software",
        "voip telephone service",
        "multilocation",
        "med spa",
        "family practice",
        "plastic surgery",
        "computer software: prepackaged software",
        "technology",
        "software development",
        "customer relationship management",
        "practice analytics dashboard",
        "patient communication automation",
        "patient appointment management",
        "patient review automation",
        "healthcare practice software",
        "practice management integration",
        "practice analytics and insights",
        "practice management data analytics",
        "patient communication optimization",
        "practice operations",
        "communication workflow automation",
        "practice marketing analytics",
        "practice management ai tools",
        "healthtech",
        "healthcare customer engagement",
        "email marketing automation",
        "ai-enhanced practice operations",
        "practice revenue optimization",
        "patient outreach tools",
        "online payment solutions",
        "practice marketing automation",
        "online scheduling",
        "ai-powered growth tools",
        "practice analytics",
        "customer experience",
        "practice automation",
        "patient satisfaction tools",
        "ai-enabled practice automation",
        "practice marketing metrics",
        "medical practice solutions",
        "practice marketing",
        "practice revenue",
        "ai in healthcare",
        "practice workflow automation",
        "automated patient recall",
        "call recording and transcription",
        "patient reviews",
        "medical practice software",
        "ai-driven practice insights",
        "hipaa compliance",
        "ai-powered tools",
        "practice growth tools",
        "practice marketing campaign management",
        "practice marketing insights",
        "insurance verification",
        "healthcare practice marketing",
        "patient engagement analytics",
        "practice efficiency",
        "ai call transcription",
        "practice revenue growth tools",
        "practice management ai technology",
        "ai-enhanced customer reviews",
        "patient sentiment detection",
        "patient sentiment analysis",
        "patient feedback management",
        "healthcare software",
        "practice management platform",
        "practice operations optimization",
        "practice growth",
        "practice scheduling software",
        "practice revenue cycle management",
        "patient communication system",
        "practice communication tools",
        "payment integration",
        "patient satisfaction",
        "healthcare practice growth",
        "patient review management",
        "practice management system integration",
        "payment processing",
        "practice revenue management ai",
        "text messaging platform",
        "practice marketing optimization",
        "practice management software",
        "ai-powered patient outreach",
        "patient engagement",
        "ai-driven patient reactivation",
        "practice efficiency software",
        "patient engagement platform",
        "practice marketing solutions",
        "ai-driven appointment reminders",
        "small business healthcare",
        "call intelligence",
        "practice marketing personalization",
        "practice management workflow",
        "practice management ai integration",
        "practice revenue analytics",
        "patient communication app",
        "billing and payments",
        "practice revenue enhancement",
        "ai-driven patient engagement strategies",
        "ai-enabled payment plans",
        "ai-enabled practice analytics",
        "reputation management",
        "automated reminders",
        "patient communication",
        "practice management ai solutions",
        "patient outreach automation",
        "text to pay",
        "practice marketing platform",
        "hipaa compliant messaging",
        "patient retention",
        "healthcare practice management",
        "patient retention strategies",
        "practice communication platform",
        "communication platform",
        "customer experience management",
        "practice revenue recovery",
        "practice marketing campaigns",
        "practice growth solutions",
        "appointment reminders",
        "ai-driven practice growth strategies",
        "practice management solutions",
        "practice marketing ai",
        "ai-driven practice growth",
        "ai review response",
        "ai-enhanced patient communication",
        "practice marketing automation tools",
        "ai-driven practice marketing",
        "patient data management",
        "b2b",
        "services",
        "health, wellness & fitness",
        "hospital & health care",
        "physiotherapy",
        "financial services",
        "information technology & services",
        "crm",
        "sales",
        "enterprise software",
        "enterprises",
        "computer software"
      ],
      "organization_revenue_printed": "213.0M",
      "organization_revenue": 212950000.0,
      "industries": [
        "information technology & services"
      ],
      "secondary_industries": [],
      "snippets_loaded": true,
      "industry_tag_id": "5567cd4773696439b10b0000",
      "industry_tag_hash": {
        "information technology & services": "5567cd4773696439b10b0000"
      },
      "retail_location_count": 0,
      "raw_address": "3401 north thanksgiving way, lehi, utah, united states",
      "street_address": "3401 North Thanksgiving Way",
      "city": "Lehi",
      "state": "Utah",
      "country": "United States",
      "postal_code": "84043",
      "owned_by_organization_id": null,
      "short_description": "Weave Communications, Inc. is a prominent customer experience and payments software platform tailored for small and medium-sized healthcare businesses. Based in Lehi, Utah, Weave enhances practice efficiency and profitability by streamlining communication, billing, and patient engagement workflows. The company has earned recognition as a G2 leader in Patient Relationship Management software and has been named a Top 50 Product for Small Business.\n\nWeave offers an integrated suite of tools that support the entire patient journey. This includes a sophisticated phone system with automated scheduling and messaging, seamless billing and payment integration, and an AI-powered platform launched in 2024 that automates tasks like appointment management. Weave also collaborates with third-party platforms to expand its functionality for healthcare providers. The company primarily serves dental, optometry, and general medical practices, helping them attract and retain patients while optimizing their financial workflows.",
      "departmental_head_count": {
        "finance": 11,
        "support": 143,
        "operations": 38,
        "engineering": 182,
        "sales": 263,
        "accounting": 11,
        "information_technology": 16,
        "administrative": 3,
        "marketing": 32,
        "arts_and_design": 18,
        "human_resources": 10,
        "data_science": 2,
        "product_management": 23,
        "business_development": 16,
        "entrepreneurship": 7,
        "media_and_commmunication": 5,
        "education": 11,
        "legal": 3,
        "consulting": 4
      },
      "intent_strength": null,
      "show_intent": false,
      "has_intent_signal_account": false,
      "intent_signal_account": null,
      "generic_org_insights": null,
      "organization_headcount_six_month_growth": null,
      "organization_headcount_twelve_month_growth": null,
      "organization_headcount_twenty_four_month_growth": null
    },
    {
      "id": "679059f0fd228301b2234207",
      "name": "Bild AI",
      "website_url": "http://www.bild.ai",
      "blog_url": null,
      "angellist_url": null,
      "linkedin_url": "http://www.linkedin.com/company/bild-ai",
      "twitter_url": null,
      "facebook_url": null,
      "primary_phone": {},
      "languages": [],
      "alexa_ranking": null,
      "phone": null,
      "linkedin_uid": "105593757",
      "founded_year": null,
      "publicly_traded_symbol": null,
      "publicly_traded_exchange": null,
      "logo_url": "https://zenprospect-production.s3.amazonaws.com/uploads/pictures/68a803286870dd0001926a22/picture",
      "crunchbase_url": null,
      "primary_domain": "bild.ai",
      "industry": "information technology & services",
      "estimated_num_employees": 4,
      "keywords": [
        "technology, information & internet",
        "ai blueprint reading",
        "permitting automation",
        "blueprint accuracy",
        "blueprint error resolution",
        "blueprint error flagging",
        "regulation validation",
        "regulation compliance check",
        "cost estimation",
        "regulation compliance",
        "regulation adherence verification",
        "blueprint validation",
        "error detection",
        "blueprint upload",
        "blueprint discrepancy detection",
        "permitting accuracy",
        "error flagging",
        "cost breakdowns",
        "regulation validation tools",
        "cost estimation tools",
        "construction",
        "automated blueprint review",
        "permitting time reduction",
        "discrepancy identification",
        "regulatory standards",
        "permitting process automation",
        "discrepancy review",
        "software",
        "regulatory compliance tools",
        "discrepancy flagging",
        "project plan analysis",
        "internal consistency",
        "ai blueprint analysis",
        "blueprint consistency check",
        "ai-powered platform",
        "project plan extraction",
        "project plan validation",
        "code compliance detection",
        "error resolution",
        "cost accuracy improvement",
        "ai estimation",
        "b2b",
        "services",
        "information technology & services",
        "computer software"
      ],
      "organization_revenue_printed": null,
      "organization_revenue": 0.0,
      "industries": [
        "information technology & services"
      ],
      "secondary_industries": [],
      "snippets_loaded": true,
      "industry_tag_id": "5567cd4773696439b10b0000",
      "industry_tag_hash": {
        "information technology & services": "5567cd4773696439b10b0000"
      },
      "retail_location_count": 0,
      "raw_address": "san francisco, california, united states",
      "street_address": "",
      "city": "San Francisco",
      "state": "California",
      "country": "United States",
      "postal_code": null,
      "owned_by_organization_id": null,
      "short_description": "Making building affordable by leveraging AI to analyze blueprints. Currently serving clients who do flooring, lumber, and door takeoffs for material cost estimation. Backed by investors of PlanGrid, Dropbox, and Airbnb (YCW25).",
      "departmental_head_count": {
        "entrepreneurship": 2,
        "accounting": 0,
        "sales": 0,
        "operations": 0,
        "finance": 0,
        "marketing": 0,
        "human_resources": 0,
        "information_technology": 0,
        "legal": 0,
        "engineering": 0,
        "business_development": 0,
        "product_management": 0,
        "consulting": 0,
        "education": 0,
        "administrative": 0,
        "media_and_commmunication": 0,
        "arts_and_design": 0,
        "support": 0,
        "data_science": 0
      },
      "intent_strength": null,
      "show_intent": false,
      "has_intent_signal_account": false,
      "intent_signal_account": null,
      "generic_org_insights": null,
      "organization_headcount_six_month_growth": null,
      "organization_headcount_twelve_month_growth": null,
      "organization_headcount_twenty_four_month_growth": null
    },
    ]
}
]
#Get org ids
org_ids = []
org_domains = []
for org in enriched:
    org_data = org.get("organizations") #returns a list of dicts
    for each_org in org_data:
        org_id = each_org.get("id")
        org_ids.append(org_id)
        org_domain = each_org.get("primary_domain")
        org_domains.append(org_domain)

print(f"The org ids are {org_ids}")
print(f"The org domains are {org_domains}")