#This file contains keywords that we'll use to score every lead's keywords

ai_keywords = {
    "high_signal": [
        "data labeling",
        "data annotation",
        "human-in-the-loop",
        "data tagging",
        "dataset preparation",
        "data verification",
        "data curation",
        "ground truth",
        "annotation workforce",
        "training data quality",
        "labeled dataset",
        "annotation platform",
        "data cleaning",
        "data validation",
    ],
    "medium_signal": [
        "computer vision",
        "natural language processing",
        "nlp",
        "speech recognition",
        "image recognition",
        "language model",
        "ai training data",
        "synthetic data",
        "machine learning operations",
        "mlops",
        "data pipeline",
        "data engineering",
        "ai dataset",
        "feature engineering",
    ],
    "low_signal": [
        "artificial intelligence",
        "ai",
        "machine learning",
        "deep learning",
        "ai research",
        "neural networks",
        "predictive analytics",
        "ai startup",
        "ai platform",
        "ai solutions",
        "data science",
    ],
}
